#!/bin/bash

is_overview_active() {
    gdbus call --session \
        --dest org.gnome.Shell \
        --object-path /org/gnome/Shell \
        --method org.freedesktop.DBus.Properties.Get \
        org.gnome.Shell OverviewActive | grep -q "true"
}

unlocked() {
    wofi_kill &
	# Check if wofi is running
	if pgrep -x "wofi" > /dev/null; then
	# Wofi is running; simulate pressing Enter
        pkill -x wofi
	fi
	
# Options for the wofi menu
OPTIONS="1. Scale display to 300%\n2. Scale display to 275%\n3. Scale display to 250%\n4. Scale display to 200%\n5. Scale display to 150%\n6. Scale-to-fit true\n7. Scale-to-fit false\n8. Close"

# Display the menu and capture the user's selection
SELECTION=$(echo -e "$OPTIONS" | wofi -d --prompt "Select an option:" --lines 8)

# Execute a command based on the selection
case "$SELECTION" in
    "1. Scale display to 300%")
        wlr-randr --output "HWCOMPOSER-1" --scale 3.00
        ;;
    "2. Scale display to 275%")
        wlr-randr --output "HWCOMPOSER-1" --scale 2.75
        ;;
    "3. Scale display to 250%")
        wlr-randr --output "HWCOMPOSER-1" --scale 2.50
        ;;
    "4. Scale display to 200%")
        wlr-randr --output "HWCOMPOSER-1" --scale 2.00
        ;;
    "5. Scale display to 150%")
        wlr-randr --output "HWCOMPOSER-1" --scale 1.50
        ;;
    "6. Scale-to-fit true")
        gsettings set sm.puri.phoc scale-to-fit true
        ;;
    "7. Scale-to-fit false")
        gsettings set sm.puri.phoc scale-to-fit false
        ;;
    "8. Close")
        pkill -x wofi
        ;;
esac

}

# Function to toggle the flashlight
locked() {
    current_brightness=$(dbus-send --session --dest=org.droidian.Flashlightd --print-reply=literal \
                    /org/droidian/Flashlightd org.freedesktop.DBus.Properties.Get \
                    string:org.droidian.Flashlightd string:Brightness | awk '{print $3}')

    if [ "$current_brightness" -eq 0 ]; then
        # Turn on the flashlight
        dbus-send --session --dest=org.droidian.Flashlightd --type=method_call /org/droidian/Flashlightd org.droidian.Flashlightd.SetBrightness uint32:31
        echo "Flashlight turned on"
	sleep 20
        dbus-send --session --dest=org.droidian.Flashlightd --type=method_call /org/droidian/Flashlightd org.droidian.Flashlightd.SetBrightness uint32:0
    else
        # Turn off the flashlight
        dbus-send --session --dest=org.droidian.Flashlightd --type=method_call /org/droidian/Flashlightd org.droidian.Flashlightd.SetBrightness uint32:0
        echo "Flashlight turned off"
    fi
}

wofi_kill () {
dbus-monitor "interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/org/gnome/Shell'" | \
while read -r line; do
    # Check if the OverviewActive property has changed
    if echo "$line" | grep -q "string \"OverviewActive\""; then
        # Read the next line for the boolean value
        read -r next_line
        if echo "$next_line" | grep -q "boolean true"; then
            if pgrep -x wofi > /dev/null; then
          pkill -x wofi
        fi
            break
        fi
    fi
done
}

# Identify the session ID
session_id=$(loginctl list-sessions | grep $(whoami) | awk 'NR==2 {print $1}')
# Check lock status of the session
idle_hint=$(loginctl show-session $session_id -p LockedHint)

if [[ "$idle_hint" == *"yes"* ]]; then
    locked
    echo "Locked"
elif [[ "$idle_hint" == *"no"* ]]; then
    if is_overview_active; then
        pkill -x wofi
        wtype -M win -k Super_l
        unlocked
    else
        unlocked
    fi
else 
    echo "Failed to determine lockscreen state"
fi
