#!/bin/bash

unlocked() {
    wtype -k Control_L+C
}

# Function to toggle the flashlight
locked() {
    current_brightness=$(dbus-send --session --dest=org.droidian.Flashlightd --print-reply=literal \
                    /org/droidian/Flashlightd org.freedesktop.DBus.Properties.Get \
                    string:org.droidian.Flashlightd string:Brightness | awk '{print $3}')

    if [ "$current_brightness" -eq 0 ]; then
        # Turn on the flashlight
        dbus-send --session --dest=org.droidian.Flashlightd --type=method_call /org/droidian/Flashlightd org.droidian.Flashlightd.SetBrightness uint32:31
        echo "Flashlight turned on"
	sleep 20
        dbus-send --session --dest=org.droidian.Flashlightd --type=method_call /org/droidian/Flashlightd org.droidian.Flashlightd.SetBrightness uint32:0
    else
        # Turn off the flashlight
        dbus-send --session --dest=org.droidian.Flashlightd --type=method_call /org/droidian/Flashlightd org.droidian.Flashlightd.SetBrightness uint32:0
        echo "Flashlight turned off"
    fi
}


# Identify the session ID
session_id=$(loginctl list-sessions | grep $(whoami) | awk 'NR==2 {print $1}')
# Check lock status of the session
idle_hint=$(loginctl show-session $session_id -p LockedHint)

if [[ "$idle_hint" == *"yes"* ]]; then
    locked
    echo "Locked"
elif [[ "$idle_hint" == *"no"* ]]; then
    unlocked
    echo "Unlocked"
else 
    echo "Failed to determine lockscreen state"
fi