#!/bin/bash

yad --name="fastflx1" \
    --title="FastFLX1" \
    --text="Fast tweaks for FLX1" \
    --text-align=center \
    --form \
    --field="Go to staging":fbtn "kgx -- bash -c 'sudo apt install furios-apt-config-staging furios-apt-config-debian-staging -y && sudo apt update && sudo apt install furios-apt-config-krypton-staging -y && sudo apt update && sudo apt upgrade -y --allow-downgrades && sudo apt update && sudo apt upgrade -y --allow-downgrades'" \
    --field="Go to production":fbtn "kgx -- bash -c 'sudo apt remove furios-apt-config-staging furios-apt-config-debian-staging furios-apt-config-krypton-staging -y && sudo apt update && sudo apt upgrade -y --allow-downgrades && sudo apt update && sudo apt upgrade -y --allow-downgrades'" \
    --field="Install/remove Branchy app":fbtn "kgx -e 'bash -c \"if dpkg -l | grep -q furios-app-branchy; then sudo apt remove -y furios-app-branchy; else sudo apt install -y furios-app-branchy; fi\"'" \
    --field="Upgrade FuriOS":fbtn "kgx -- bash -c 'sudo apt update && sudo apt upgrade -y --allow-downgrades && sudo apt update && sudo apt upgrade -y --allow-downgrades'" \
    --field="Set city to Weather":fbtn "kgx -- bash -c 'gnome-weather-location'" \
    --field="Start Tweak services":fbtn "bash -c 'notify-send \"Tweak services started\" --icon=\"/home/furios/.git/fastflx1/files/fastflx1.svg\" && dialtone & alarmvol & gen-thumbnails & gesture-shortcuts & vol-buttons & selfdestroy'" \
    --field="Stop Tweak services":fbtn "bash -c 'pgrep -f \"vol-shortcuts\" | grep -v \"$(basename $0)\" | xargs kill -9 && pgrep -f \"dialtone\" | grep -v \"$(basename $0)\" | xargs kill -9 && pgrep -f \"alarmvol\" | grep -v \"$(basename $0)\" | xargs kill -9 && pgrep -f \"gen-thumbnails\" | grep -v \"$(basename $0)\" | xargs kill -9 && pgrep -f \"gesture-shortcuts\" | grep -v \"$(basename $0)\" | xargs kill -9 && pgrep -f \"vol-buttons\" | grep -v \"$(basename $0)\" | xargs kill -9 && pgrep -f \"selfdestroy\" | grep -v \"$(basename $0)\" | xargs kill -9 && notify-send \"Tweak services stopped\" --icon=\"/home/furios/.git/fastflx1/files/fastflx1.svg\"'" \
    --field="Change Squeekboard scale":fbtn "bash -c 'squeekboard-scale'" \
    --buttons-layout=center \
    --button="Quit"