#!/bin/bash

unlocked() {
	# Check if wofi is running
	if pgrep -x "wofi" > /dev/null; then
	# Wofi is running; simulate pressing Enter
        wtype -P 'down' -p 'down'
        exit 0
	fi

# Options for the wofi menu
OPTIONS="1. Copy Ctrl+C\n2. Paste Ctrl+V\n3. Cut Ctrl+X\n4. Paste to Terminal (Wl-paste)\n5. Select all & copy Ctrl+A Ctrl+C\n6. Kill active window\n7. Show notification drawer\n8. Close"

# Display the menu and capture the user's selection
SELECTION=$(echo -e "$OPTIONS" | wofi -d --prompt "Select an option:" --lines 8)

# Execute a command based on the selection
case "$SELECTION" in
    "1. Copy Ctrl+C")
        wtype -M ctrl c -m ctrl
        ;;
    "2. Paste Ctrl+V")
        wtype -M ctrl v -m ctrl
        ;;
    "3. Cut Ctrl+X")
        wtype -M ctrl x -m ctrl
        ;;
    "4. Paste to Terminal (Wl-paste)")
        clipboard_content=$(wl-paste)
        if [[ -z "$clipboard_content" ]]; then
            notify-send "Clipboard is empty."
            exit 1
        fi
        wtype "$clipboard_content"
        ;;
    "5. Select all & copy Ctrl+A Ctrl+C")
        wtype -M ctrl a -m ctrl && wtype -M ctrl c -m ctrl
        ;;
    "6. Kill active window")
        wtype -M alt -P F4 -m alt -p F4
        ;;
    "7. Show notification drawer")
        wtype -M logo v -m logo
        ;;
    "8. Close")
        pkill -x wofi
        ;;
esac

}

# Function to toggle feedback profile
locked() {
	# Find current feedback profile
	current_profile=$(gsettings get org.sigxcpu.feedbackd profile | tr -d "'")

	# Give index numbers to profiles
	profiles=("full" "quiet" "silent")

	# Find the index of the current profile

	for i in "${!profiles[@]}"; do

	if [[ "${profiles[$i]}" == "$current_profile" ]]; then

	current_index=$i

	break

	fi
	
	done

	# Calculate the next profile index (cycling back to 0 after the last one)

	next_index=$(( (current_index + 1) % ${#profiles[@]} ))

	# Set the next profile

	gsettings set org.sigxcpu.feedbackd profile "${profiles[$next_index]}"
}


# Identify the session ID
session_id=$(loginctl list-sessions | grep $(whoami) | awk 'NR==2 {print $1}')
# Check lock status of the session
idle_hint=$(loginctl show-session $session_id -p LockedHint)

if [[ "$idle_hint" == *"yes"* ]]; then
    locked
    echo "Locked"
elif [[ "$idle_hint" == *"no"* ]]; then
    unlocked
    echo "Unlocked"
else 
    echo "Failed to determine lockscreen state"
fi
