#!/bin/bash

# Start feh and immediately wait for it to finish
start_feh() {
    feh --fullscreen "${HOME}/.git/fastflx1/files/tux.jpg"
    pkill -x wofi
}

# Function to start wofi
start_wofi() {
# Get the current value of the keyboard scale
current_scale=$(gsettings get sm.puri.Squeekboard keyboard-scale)
notify-send "Your current scale is $current_scale" --icon="/home/furios/.git/fastflx1/files/fastflx1.svg"

# Options for the FastFLX1 tweaks menu
OPTIONS="1. Scale Squeekboard to 1.00\n2. Scale Squeekboard to 1.10\n3. Scale Squeekboard to 1.15\n4. Scale Squeekboard to 1.20\n5. Scale Squeekboard to 1.25\n6. Scale Squeekboard to 1.30\n7. Scale Squeekboard to 1.35\n8. Quit"

# Display the menu and capture the user's selection using wofi
SELECTION=$(echo -e "$OPTIONS" | wofi -d --prompt "Select an option:" --lines 8)

# Wait for feh to exit
wait $FEH_PID

# Execute a command based on the selection
case "$SELECTION" in
    "1. Scale Squeekboard to 1.00")
        pkill -x feh
        gsettings set sm.puri.Squeekboard keyboard-scale 1.00
        ;;
    "2. Scale Squeekboard to 1.10")
        pkill -x feh
        gsettings set sm.puri.Squeekboard keyboard-scale 1.10
        ;;
    "3. Scale Squeekboard to 1.15")
        pkill -x feh
        gsettings set sm.puri.Squeekboard keyboard-scale 1.15
        ;;
    "4. Scale Squeekboard to 1.20")
        pkill -x feh
        gsettings set sm.puri.Squeekboard keyboard-scale 1.20
        ;;
    "5. Scale Squeekboard to 1.25")
        pkill -x feh
        gsettings set sm.puri.Squeekboard keyboard-scale 1.25
        ;;
    "6. Scale Squeekboard to 1.30")
        pkill -x feh
        gsettings set sm.puri.Squeekboard keyboard-scale 1.30
        ;;
    "7. Scale Squeekboard to 1.35")
        pkill -x feh
        gsettings set sm.puri.Squeekboard keyboard-scale 1.35
        ;;
    "8. Quit")
        pkill -x feh
        exit 0
        ;;
    *)
        echo "Invalid selection. Exiting."
        pkill -x feh
        exit 1
        ;;
esac 
pkill -x wofi }

# Start feh in background and then wofi
start_feh &  # Start feh in the background
start_wofi  # Start wofi